# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

source 'https://github.com/CocoaPods/Specs.git'

link_with ['TextDig', 'TextDigTests']

pod 'PureLayout'
pod 'AFNetworking'
pod 'AWSiOSSDKv2'
pod 'AWSCognitoSync'